name: rtsp2mjpg

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-docker-image:
    runs-on: self-hosted-linux

    env:
        IMAGE_NAME: rtsp2mjpg

    steps:    
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Build docker image
        run: docker build . --file Dockerfile -t docker-registry.home/${{ env.IMAGE_NAME }}:latest && docker push docker-registry.home/${{ env.IMAGE_NAME }} --all-tags